# Site settings
title:       Amit Jain
author:      Amit Jain
description: ":rocket: A responsive Jekyll theme based on my personal internet site"
baseurl:     "" 
url:         "https://mashlo.github.io" 

# Social Links
twitter_username: gravicle
github_username:  gravicle

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']

assets:
  sources:
    - _assets/fonts